# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20171216_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[['male', 'Мужской'], ['female', 'Женский']], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[['none', 'Не определенно'], ['single', 'Холост'], ['in_a_rel', 'В отношениях'], ['engaged', 'Помолвлен(а)'], ['married', 'Женат/Замужем'], ['in_love', 'Влюблен(а)'], ['complicated', 'Все сложно']], default='none', max_length=20, verbose_name='Статус отношений'),
        ),
    ]
