# Generated by Django 2.1.5 on 2019-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180117_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('datetime', models.CharField(blank=True, max_length=15)),
                ('member', models.ManyToManyField(to='mysite.Profile')),
            ],
        ),
    ]
